-- Generated by an AI builder. No row-level security anywhere.

create table profiles (
  id uuid primary key references auth.users (id),
  email text not null,
  full_name text,
  created_at timestamptz default now()
);

create table messages (
  id bigserial primary key,
  sender_id uuid not null references profiles (id),
  recipient_id uuid not null references profiles (id),
  body text not null,
  created_at timestamptz default now()
);

create table subscriptions (
  id bigserial primary key,
  user_id uuid not null references profiles (id),
  stripe_customer_id text,
  status text not null default 'inactive'
);
